misskey-delta/misskey-api

- package.json
- src/check-dependencies.ts
> check-dependencies: use process.exec

- src/db/interfaces.ts
> db: interfaces: update type definitions

- src/endpoints/talks/messages/delete.ts
> endpoint: talks: messages: delete: use any to resolve error and refactoring

- src/core/extract-mentions.ts
> core: extract-mentions: null should be rejected

- src/config.ts
> config: drop port.internal

- src/endpoints/posts/like.ts
- src/endpoints/talks/group/create.ts
- src/endpoints/talks/messages/say.ts
resolve #6.
include posts/like, talk/group/create, talks/message/say.
> expand limits by suspended

- src/endpoints/posts/like.ts
change no action to no notification.
> [endpoints] posts/like: change behavior by yourself like

- package.json
> chore(package): update @types/mongoose to version 4.7.17

- package.json
> fix(package): update mongoose to version 4.10.5

- package.json
> fix(package): update hapi-plugin-websocket to version 1.2.2

- package.json
> chore(package): update typescript to version 2.3.4

- package.json
> chore(package): update @types/ws to version 3.0.0

- package.json
> fix(package): update hapi-plugin-websocket to version 1.2.8

- package.json
> chore(package): update @types/multer to version 1.3.2

- package.json
> chore(package): update @types/request to version 0.0.45

- package.json
> chore(package): update @types/hapi to version 16.1.6

- package.json
> fix(package): update mongoose to version 4.11.5

- package.json
> chore(package): update @types/ws to version 3.0.2

- package.json
> chore(package): update @types/request to version 2.0.0

- package.json
> fix(package): update hapi-plugin-websocket to version 1.2.15

- package.json
- src/rest-handlers/album/files/list.ts
- src/rest-handlers/album/folders/list.ts
- src/rest-handlers/users/followers.ts
- src/rest-handlers/users/following.ts
> Update tslint to 5.5.0

- package.json
- src/api-handler.ts
- src/authenticate.ts
- src/config.ts
> Implement authorization with token

- package.json
> fix(package): update hapi-plugin-websocket to version 1.2.17

- package.json
> chore(package): update @types/request to version 2.0.4

- package.json
> fix(package): update mongoose to version 4.12.0

- package.json
> fix(package): update connect-redis to version 3.3.2

- package.json
> fix(package): update hapi to version 16.6.2

- package-lock.json
- package.json
- src/core/add-file-to-album.ts
> improve core/add-file-to-album
